cat<<BABY > database_setup.sql
FLUSH PRIVILEGES;
GRANT ALL ON *.* TO 'root'@'%' identified by '$SQL_ROOT_PASSWORD' WITH GRANT OPTION;
GRANT ALL ON *.* TO 'root'@'localhost' identified by '$SQL_ROOT_PASSWORD' WITH GRANT OPTION;
DROP DATABASE IF EXISTS $SQL_USER;
CREATE OR REPLACE DATABASE $SQL_DATABASE;
CREATE USER '$SQL_USER'@'localhost' IDENTIFIED BY '$SQL_PASSWORD';
CREATE USER '$SQL_USER'@'%' IDENTIFIED BY '$SQL_PASSWORD';
GRANT ALL ON $SQL_DATABASE.* TO '$SQL_USER'@'localhost' WITH GRANT OPTION;
GRANT ALL ON $SQL_DATABASE.* TO '$SQL_USER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
BABY