version: "3.3"

services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress_volume:/usr/share/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress_volume:/usr/share/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - 9000

networks:
  inception:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/emtran/data/wordpress_volume
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/emtran/data/mariadb_volume

